Repository milieuinfo/webcomponent-vl-ui-infotext, pull requests merged in 2020-02, with the labels that each got.

#17 [FEATURE] - Wijzigende tekst/waarde moet opnieuw een fit uitvoeren
  demo/vl-infotext.html
  test/unit/vl-infotext.test.html
  vl-infotext.src.js
Labels: enhancement

#19 Stijl import vervangen door inhoud, probleem met absolute paden
  package-lock.json
  package.json
  src/vl-infotext.src.js
Labels: bug

#20 Nieuwe structuur en build scripts implementatie vervangen door vl-ui-util build implementatie
  CODEOWNERS
  bamboo-specs/bamboo.yml
  demo/vl-infotext.html
  docker-compose-release.yml
  package-lock.json
  package.json
  src/index.js
  src/style.css
  src/vl-infotext.js
  src/vl-infotext.src.js
  style.css.map
  test/docker-compose.yml
  test/e2e/infotext.test.js
  test/unit/vl-infotext.test.html
  vl-infotext.min.js
  vl-infotext.src.js
Labels: chore
