Repository milieuinfo/webcomponent-vl-ui-infotext, pull requests merged in 2020-01, with the labels that each got.

#4 #3 Ondersteuning om infotext dynamisch aan te maken (#3)
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  package.json
  style.css
  style.css.map
  test/unit/vl-infotext.test.html
  vl-infotext.src.js
Labels: enhancement

#7 Verwijder pretest fase (installeren chromedriver). Deze komt via vl-ui-util binnen
  package.json
Labels: chore

#5 Overbodig NPM release import scripts verwijderd
  package.json
Labels: maintenance

#6 Update vl-ui-util
  package-lock.json
  package.json
  style.css
  test/docker-compose.yml
Labels: maintenance

#8 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: maintenance

#13 #12: Docker-compose voor release gebruiken
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.css.map
  docker-compose-release.yml
  package-lock.json
  package.json
  style.css
  style.css.map
Labels: bug

#14 Update vl-ui-util
  package-lock.json
Labels: maintenance

#15 Lange teksten moeten binnen de badge blijven
  demo/vl-infotext.html
  package-lock.json
  test/unit/vl-infotext.test.html
  vl-infotext.src.js
Labels: bug
